### ISSUE TITLE
Error & Question of testing bebop SDK 

### ISSUE THREAD

**Issue by qwe953751** [lukaslaobeyer/libdrone#1]
Hi, I’m the graduate students of National Taipei University of Technology, majoring in Electrical Engineering, Taiwan. I’m doing the research of image processing which is using Parrot Bebop Drone. About the SDK of Parrot Bebop Drone, I wonder if there is any mistake of my specification?
PC’s working specifications:
Operation System: Windows 8.1 
Compiler: Visual Studio 2012
Addition Library: OpenCV 3.0.0, FFmpeg-3.0, Boost_1_58_0, Eigen-3_0_1
Here’s the error that I encounter: 
libdrone-master\include\ commands.h
![image](https://cloud.githubusercontent.com/assets/17944469/14018279/e50e5940-f207-11e5-9a69-c06e20f3533a.png)
error C2059 syntax error ' {'
error C2143 syntax error missing '; ' before '}'
error C2065 'TAKEOFF'  undeclared identifier
error C2590: 'takeoff' : 'only a constructor can have a base/member initializer list'
error C2334: unexpected >token(s) preceding '{'; skipping apparent function body
![image](https://cloud.githubusercontent.com/assets/17944469/14018431/bb91a17a-f208-11e5-8fbc-d7d0f568b78c.png)
error C2380: type(s) preceding 'command'  (constructor with return type, or illegal redefinition of current class-name?)

libdrone-master\src\drones\ardrone2\video\pave.h
![image](https://cloud.githubusercontent.com/assets/17944469/14018585/8f9ce574-f209-11e5-97ef-25277dffbadf.png)
error C2065: 'packed'  undeclared identifier
![image](https://cloud.githubusercontent.com/assets/17944469/14018611/aea9b6f4-f209-11e5-8190-d9df4c64471c.png)
error C2086: 'int PaVE' : redefinition

libdrone-master\src\drones\bebop\ protocol.h
![image](https://cloud.githubusercontent.com/assets/17944469/14018661/d05c52c0-f209-11e5-8f6e-9019c4a3912a.png)
IntelliSense: must be ';'

I look forward to hearing from you! Thank you very much!

**Comment by lukaslaobeyer** [comment]
I have not tested compiling this library in Visual Studio. The problem may be the incomplete support for C++11 in VS. The library compiles fine using GCC 4.8.

This document: https://msdn.microsoft.com/en-us/library/hh567368.aspx shows C++11 support is much better in VS 2015, so maybe you can try that?

**Comment by qwe953751** [comment]
Thanks for your help! We’ll try in VS 2015 next day. Sorry for reply so late. These days we have changed the compiler. 
PC’s working specifications:
Operation System: Windows 8.1 
Compiler: Code::Blocks 16.01 + mingw(gcc4.9.2)
Addition Library: OpenCV 2.4.9, FFmpeg, Boost-1.58, Eigen-3.2.7
Here’s the error that I encounter:
====================boost====================
C:\Program Files (x86)\boost_1_58_0\boost\asio\detail\impl\win_iocp_io_service.ipp
error: '::VerSetConditionMask' has not been declared|
error: 'VER_MAJORVERSION' was not declared in this scope|
error: 'VER_GREATER_EQUAL' was not declared in this scope|
![image](https://cloud.githubusercontent.com/assets/17944469/14069336/f19740f8-f4ca-11e5-8c95-8827eb0d7a7e.png)

C:\Program Files (x86)\boost_1_58_0\boost\asio\detail\impl\win_object_handle_service.ipp
error: '::UnregisterWaitEx' has not been declared
![image](https://cloud.githubusercontent.com/assets/17944469/14069341/fb2e6ce0-f4ca-11e5-8b2a-2f691506eebb.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14069343/fd578fc4-f4ca-11e5-906c-b560c20eff77.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14069344/0082364a-f4cb-11e5-898f-4473b4fcd34a.png)

C:\Program Files (x86)\boost_1_58_0\boost\asio\detail\impl\win_object_handle_service.ipp
error: 'RegisterWaitForSingleObject' was not declared in this scope|
![image](https://cloud.githubusercontent.com/assets/17944469/14069345/091963be-f4cb-11e5-8ffa-666cff0f33ca.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14069346/0b68cff6-f4cb-11e5-9da4-1c5fa196c597.png)
====================boost====================
====================thread====================
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\4.9.2\include\c++\thread
error: no match for 'operator<' (operand types are 'std::thread::native_handle_type {aka ptw32_handle_t}' and 'std::thread::native_handle_type {aka ptw32_handle_t}')
![image](https://cloud.githubusercontent.com/assets/17944469/14069350/15bbac4e-f4cb-11e5-978a-f3d70ee8117f.png)
====================thread====================
====================FFmpeg====================
C:\Users\3rdparty\kijineko\include\inttypes.h
error: #error "Use this header only with Microsoft Visual C++ compilers!"
![image](https://cloud.githubusercontent.com/assets/17944469/14069353/23564b34-f4cb-11e5-81ba-e77ab0a80fe9.png)

C:\Users\3rdparty\kijineko\include\inttypes.h
error: '_inline' does not name a type
![image](https://cloud.githubusercontent.com/assets/17944469/14069355/2d19e810-f4cb-11e5-8bee-1b4460b71a24.png)
====================FFmpeg====================

I look forward to hearing from you! Thank you very much!

**Comment by lukaslaobeyer** [comment]
There seems to be a problem with your boost installation. How did you build boost?

I build it from source using MinGW, following the boost-provided instructions for compiling on Unix: http://www.boost.org/doc/libs/1_60_0/more/getting_started/unix-variants.html

Also, make sure you generate your Code::Blocks project using premake5 (https://premake.github.io/).

**Comment by qwe953751** [comment]
Thanks for your help. After reinstall the boost library, the error of the boost library can be fixed. Here’s the error I encounter next:

![image](https://cloud.githubusercontent.com/assets/17944469/14241117/6b4b6436-fa7c-11e5-9dbb-d7c137169c9e.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14241129/74e06596-fa7c-11e5-972d-29e21811b1f8.png)

we have tried to enter the default IP:"192.168.42.1" but it still can't work!!! We still can't connect to the bebop drone. Besides, in order to use the bebop drone, is there any process we need to follow or install? Can you give me some advice about this? Thanks a lot!  :)

**Comment by qwe953751** [comment]
Hi! We have fixed the problem mentioned above. But we have encountered another problem. The code cannot connect to Bebop and then it will shut down as below.
code error:    drone::connectionstatus status = _drone->connect();
![image](https://cloud.githubusercontent.com/assets/17944469/14463771/f749000a-00fe-11e6-9351-dec886575f2c.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14463832/38da25da-00ff-11e6-9c4a-5693ba6492a0.png)
debug error:
![image](https://cloud.githubusercontent.com/assets/17944469/14463836/3ce452b8-00ff-11e6-8a22-02135780c6e2.png)

In addition, we want to ask for your help about how to use some function of Bebop, like the function of getting image, the function of controlling Bebop moving action, and the function of getting raw, pitch, yaw of Bebop. Thank you very much!

I look forward to hearing from you! Thank you very much!

**Comment by lukaslaobeyer** [comment]
Can you send me the full stack trace of the exception?

[This example](https://github.com/lukaslaobeyer/libdrone/blob/74436429dec5031a3f416183f5e5b169d2cc1054/examples/basic/basictest.cpp) shows how some basic things like takeoff/landing and sensor data retrieval work.

**Comment by qwe953751** [comment]
Hi! Here’s the full stack trace of the exception. I pressed debug button to debug step by step.

![image](https://cloud.githubusercontent.com/assets/17944469/14529688/52f5b81e-0288-11e6-9582-613b007543a7.png)

C:\Program Files (x86)\boost_1_58_0\boost\throw_exception.hpp
![image](https://cloud.githubusercontent.com/assets/17944469/14529693/5b3fd680-0288-11e6-89ad-48cbbeb53fd3.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14529695/5e683c44-0288-11e6-8b64-f20054bc7f48.png)

C:\Program Files (x86)\boost_1_58_0\boost\asio\detail\impl\throw_error.ipp
![image](https://cloud.githubusercontent.com/assets/17944469/14529704/68bdc5c4-0288-11e6-99c8-3449a633614f.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14529712/6fd57460-0288-11e6-9cdb-aca842383f25.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14529715/71f6b89e-0288-11e6-989a-f06fe0656641.png)

C:\Program Files (x86)\boost_1_58_0\boost\exception\exception.hpp
![image](https://cloud.githubusercontent.com/assets/17944469/14529720/7b11ff38-0288-11e6-88e5-070eb9a0635f.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14529724/7dee65ac-0288-11e6-8d12-ebada6a80dda.png)

C:\Program Files (x86)\boost_1_58_0\boost\asio\detail\impl\throw_error.ipp
![image](https://cloud.githubusercontent.com/assets/17944469/14529729/85916232-0288-11e6-8a2f-ee9093bc22f2.png)
![image](https://cloud.githubusercontent.com/assets/17944469/14529734/88593f44-0288-11e6-9611-71e6b9f6cc9f.png)

Thank you very much !!!!!

I look forward to hearing from you! =)

**Comment by lukaslaobeyer** [comment]
So it looks to me like the exception is thrown somewhere near [here](https://github.com/lukaslaobeyer/libdrone/blob/master/src/drones/bebop/controllink.cpp#L104).

Could you tell me what the thrown exception is exactly? Also, make sure you don't have any firewall trying to block your program.

Actually, connect() should not throw at all, so if you could wrap it into a `try` block like so and send me the output that'd be helpful as well:

``` c++
try
{
    _drone->connect();
}
catch(const std::exception &e)
{
    std::cerr << e.what() << std::endl;
}
```
